"""Update database: User: password changed to hashed_password

Revision ID: 88044e779627
Revises: 7f430a414ed2
Create Date: 2025-09-24 14:23:48.602364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88044e779627'
down_revision: Union[str, Sequence[str], None] = '7f430a414ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
